version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    command: npm run dev
    ports:
     - "${APP_PORT}:3000"
  mysql:
    extends:
        file: docker-compose.base.yml
        service: mysql
    ports:
     - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
networks:
  app-net:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"