version: '2'
services:
  app:
    working_dir: /app
    image: node:9
    container_name: hapidocker
    environment:
      HOST: 0.0.0.0
    volumes:
     - .:/app
    networks:
     - app-net
  mysql:
    image: mysql:5.7
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - app-net
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - app-net